// auth
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// vocabulary
export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const GET_USER_INFO='GET_USER_INFO'
// export const TRANSLATE_WORD='TRANSLATE_WORD'
// export const DICTIONARY_WORD='DICTIONARY_WORD'
export const GET_USER_LANGUAGE_WORDS='GET_USER_LANGUAGE_WORDS'
export const GET_ALL_LANGUAGE_OPTIONS='GET_ALL_LANGUAGE_OPTIONS'
export const SET_USER_LANGUAGE='SET_USER_LANGUAGE'
export const ADD_WORD='ADD_WORD'
export const ADD_COMPONENT='ADD_COMPONENT'
export const SET_TEXT_INPUT='SET_TEXT_INPUT'